kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: migrateme
  namespace: default
spec:
  serviceName: kubernetes
  replicas: 1
  selector:
    matchLabels:
      app: migrateme
  template:
    metadata:
      labels:
        app: migrateme
      annotations:
        anthos-migrate.gcr.io/action: run
        anthos-migrate.gcr.io/source-type: vlsdisk
        # source-pvc needs to match the name of the PVC declared above.
        anthos-migrate.gcr.io/source-pvc: test
    spec:
      containers:
      - name: migrateme
      # The image for the Migrate for Anthos system container.
        image: anthos-migrate.gcr.io/v2k-run:v0.9.7
